events {}

http {
    types {
        text/html                   html htm;
        text/css                    css;
        application/javascript      js;
        application/json            json;
        image/png                   png;
        image/jpeg                  jpg jpeg;
        image/gif                   gif;
        image/svg+xml               svg;
        image/x-icon                ico;
        font/woff                   woff;
        font/woff2                  woff2;
        application/octet-stream    bin;
    }

    default_type application/octet-stream;

    server {
        listen 0.0.0.0:80;
        root /app;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        gzip on;
        gzip_types text/css application/javascript text/html;
    }
}
