[phases.setup]
nixPkgs = ["nginx"]
cmds = ["mkdir -p /etc/nginx/ /var/log/nginx/ /var/cache/nginx/"]

[phases.install]
cmds = []

[phases.build]
cmds = ["cp -r /app /usr/share/nginx/html-app"]

[start]
cmd = "nginx -c /app/nginx.conf -g 'daemon off;'"
